version: '3'

services:
  eos_payload:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    depends_on:
      - mosquitto
    network_mode: "host"
    volumes:
      - ./eos_artifacts:/usr/src/app/eos_artifacts
      - .:/usr/src/app:ro

  mosquitto:
    image: eclipse-mosquitto:2
    network_mode: "host"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro