version: '3.4'

services:
  eos_payload:
    build:
      context: .
      network: host
      dockerfile: Dockerfile
    privileged: true
    depends_on:
      - mosquitto
    network_mode: "host"
    volumes:
      - /media/card/eos_artifacts:/usr/src/app/eos_artifacts
      - .:/usr/src/app:ro
      - /run/udev:/run/udev:ro
      - /dev:/dev
    restart: always

  mosquitto:
    image: eclipse-mosquitto:2
    network_mode: "host"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:rw
    restart: always